version: "3.8"
services:
  db:
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql
  web:
      build: .
      command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
      volumes:
      - .:/code
      ports:
      - "80:8000"
      depends_on:
        - db

volumes:
  db-store: