# Generated by Django 4.0.6 on 2022-07-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_ready',
            new_name='status',
        ),
    ]
